### ISSUE TITLE
Support for android FF v. 120.1.1

### ISSUE THREAD

**Issue by itrn57** [conceptualspace/yet-another-speed-dial#102]
Hi 
Is is possible to add support to the recent android FF v.120.1.1 ?
Thank you.

**Comment by conceptualspace** [comment]
unfortunately firefox on mobile does not support the API to set a custom homepage, and i doubt it is likely they will add it because their default home page brings in that sweet advertising $$$

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_url_overrides
