### ISSUE TITLE
persistent storage for website logos

### ISSUE THREAD

**Issue by deathtrip** [conceptualspace/yet-another-speed-dial#18]
Right now, when there's no internet connection, all the dials that use website logos are blank. Only the dials that use screenshots are normally displayed. I assume it's because YASD fetches the logos on every browser restart. I think a persistent storage would be a better solution, so dials are always visible regardless of internet connectivity status. It would also increase privacy, as less connections would be made.

**Comment by conceptualspace** [comment]
I've considered this too, but there are a few obstances. And the most obvious question, if there is no internet connection, what am I doing in the browser?

The other consideration is that the local storage provided to extensions by chrome is really limited and slow. In testing I found it was actually faster (at least on my connection) to load the dials over the Internet than localstorage! And I sort of grew to like how some websites update their logos etc and YASD would pick that up automatically.

That said it would be worth another look because of the *potential* performance and privacy improvements. Thanks

**Comment by deathtrip** [comment]
Oftentimes i open my browser before my modem has established internet connectivity, and that's when the dials are blank, or when there's a temporary loss of connection.
Currently a website can determine when a user opens their browser and how often, by looking at the connections being made.
Maybe an option to enable local storage, so everyone can have it their preferred way.

**Comment by conceptualspace** [comment]
thats an interesting consideration. the main issue is the limitations of the storage api, where we are limited to 5MB of total storage. maybe i could create a highly compressed thumbnail for each site that is loaded if there's no network connection. that way we at least avoid blank thumbnails on unstable connections. once that is in place, enabling an offline/paranoid mode should be easy. i want to keep the settings panel as simple as possible but i might enable this as an advanced setting in the extension options page. PRs welcome! :)

**Comment by conceptualspace** [comment]
moving to backlog

**Comment by SerafDosSantos** [comment]
You could use the favicons, considering they are usually small, with an alternate default dial view.
