### ISSUE TITLE
Feature request: Remember last selected folder

### ISSUE THREAD

**Issue by glockbender** [conceptualspace/yet-another-speed-dial#27]
I use two folders: home(default) and work. All 'new tab' action shows me a dial only at home tab. But I chose 'work' folder previously. Could you add correspond setting or implement this behavior by default? I mean for new tabs focus on the last used folder. Thanks=)

**Comment by SerafDosSantos** [comment]
This is currently my main itch about YASD...

**Comment by conceptualspace** [comment]
should be pretty easy to implement, ill try to bang it into the next release

**Comment by sunjaxx** [comment]
I would suggest this to make this an option / setting: I also use multiple tabs but rather prefer to always have the first/main folder as default. 

However, if, say, I open a bookmark from "work" (i.e. not your  default one) and then go "back" using the browser back button, I would expect to end up in the "work" tab (and not the "home" one). Shouldn't this be the default / expected behavior in this scenario?

**Comment by conceptualspace** [comment]
nice catch. yes i suppose it should. we don't get this for free because YASD doesnt do any kind of routing with the extention URL (its intentionally left clear so users can easily search from the new tab page). so probably we need to add a listener on the background process to persist the page state. ill see if i can bang something into the next release or so

**Comment by glockbender** [comment]
Any updates about this feature?

**Comment by enzogianvittorio** [comment]
This is a very useful feature, and would make a huge difference. I really hope developer(s) are able to implement it.

**Comment by conceptualspace** [comment]
done. i'll add it to v2.4.0 :)
