### ISSUE TITLE
The duplication of the site title

### ISSUE THREAD

**Issue by heywolf15** [conceptualspace/yet-another-speed-dial#37]
In this case, I have a lot of sites who don't have the thumbnail after first sync to fresh Firefox.
On the Firefox after sync the bookmarks from other devices, the extension start to open a lot of tabs from the speed dial bookmark.
Like opening more than 50 tabs almost in the same time, but they close pretty fast.
When opening the speed dial tab, a lot of the site has the same title and not get the thumbnail.

To change it back I need to open the Bookmarks Library, delete the name of the site one by one and it will be using the url.
But on the Speed dial tab, it will just be an empty title. Trying to cut and paste to other folder outside speed dial and put it back. Doesn't change anything

**Comment by conceptualspace** [comment]
parallel processing of multiple bookmarks (as in case of sync/import) was overwriting global variable; reduced to local scope

**Comment by heywolf15** [comment]
The Firefox sync carried the error to the new profile
Is there a way to reset it?
Is it by re-installing the extensions?

**Comment by conceptualspace** [comment]
do you mean the bookmarks don't have the right titles? and just to confirm, you mean the titles were wrong on device A and then synced to device B, right? the bug that originally caused the problem should have been fixed in v1.15, so just want to make sure the sync isn't causing additional problems with the titles.

assuming that's correct, i have one idea to fix them up. if you're OK with using the URL as the title, we can easily run a function to assign the url as the title.

alternatively, YASD could loop through the bookmarks and fetch the <title> tag from each site, the only downside being that it could take some time to run depending on how many bookmarks you have

let me know what you think and i'll share further instructions on how to do it

**Comment by heywolf15** [comment]
> do you mean the bookmarks don't have the right titles? and just to confirm, you mean the titles were wrong on device A and then synced to device B, right? 

Yes, thats right

I have no problem with both of them. I will choose YASD so I can get proper title
Can it fetch the thumbnail too? Cause all the thumbnail gone and it will be pain to click refresh thumbnail one by one

**Comment by conceptualspace** [comment]
i'm going to push v2.1 to firefox shortly. then to update all your images: open the dev console (ctrl+shift+i)  and type this: `refreshAllThumbnails()`

**Comment by conceptualspace** [comment]
@heywolf15 to update all your titles to match the URL, open YASD and paste this code into the dev console:

```
console.log("updating titles to match urls...")
    const allFolders = folders.concat(speedDialId);
    let urls = [];

    for (let folder of allFolders) {
        let children = await browser.bookmarks.getChildren(folder);
        for (let child of children) {
            if (child.url && child.url.startsWith('http') && child.title !== child.url) {
                console.log("  >>> ", child.url)
                await browser.bookmarks.update(child.id, {
                    title: child.url
                });
            }
        }
        console.log("done!")
    }
```

that should do the trick :smile:

**Comment by heywolf15** [comment]
Thank you so much for helping me and improve it for everyone.
Already using the code to update all the titles to match the URL and it works great, even trying to fetch an icon or logo (I think?) from the sites.
But, not all the sites have a logo, so it just blanks and that's why there's an error when running the code.
Haven't tried the "refresh all the thumbnails" code,
