### ISSUE TITLE
Issue: Touch Usability (EDGE)

### ISSUE THREAD

**Issue by Schadenfreund** [conceptualspace/yet-another-speed-dial#40]
It would be great if the touch usability could be improved.

If touch controls are used, the tiles can only be activated unreliably and move around. Also hold to right click (i.e. for editing a Tile image) is not possible with touch.

**Comment by SerafDosSantos** [comment]
@conceptualspace I can test on my side and do the corrections if any arises.

**Comment by conceptualspace** [comment]
thanks for the report @Schadenfreund 

i think the issue was that on touch we only have one gesture (long tap) to trigger two functions: show the context menu or trigger drag and drop (on desktop these are easily differentiated with right click vs long click)

so ive added a delay to trigger the drag and drop; this should make it easier to open a speed dial without it moving around, and allow the context menu to show on a long tap. the only a longer tap with movement should trigger sorting with drag and drop

@SerafDosSantos the changes are in the latest commit if you want to try them :smiley:

**Comment by SerafDosSantos** [comment]
@conceptualspace Woohoo! But I'm not a big touch user... I'll have a look to the fetch later. Keep up the good work!

**Comment by Schadenfreund** [comment]
Thank you for the explanation @conceptualspace 

Just tested it with the new Update and now it works like a charm. 

Keep on rocking and all the best to you.
