### ISSUE TITLE
Feature Request: Empty Sites (for organizing)

### ISSUE THREAD

**Issue by DBecker7** [conceptualspace/yet-another-speed-dial#51]
It would just be an empty space instead of a site.

For instance, if I have 5 columns and I have three mail links, then two empty spaces, the next bookmarks will be on the next line.

Alternative, forced new lines; or multiple folders on one page (separated by white space or labels). Basically I just want to separate things visually so I can have everything on the same page.

**Comment by conceptualspace** [comment]
i like the idea; i experimented with that before in firefox because firefox has a "separator" object in its bookmarks manager, but chrome and edge have no such object, and i ended up just using folders to generally do what the separators did

it's a hack, but one idea u can do is just make a dummy bookmark (like localhost) and set a transparent image as the thumbnail

for example:
![separator](https://user-images.githubusercontent.com/4175632/152607529-d44e67d2-fb13-4cbd-938d-850998989bab.png)

**Comment by woj-tek** [comment]
(could we re-open this issue?)

Would you be open to have incosistent behaviour between browsers (i.e. have it only in Firefox)?

It would be really great to be able to have a horizontal line and split the tiles in groups like that.
