### ISSUE TITLE
Speed dials disappear 

### ISSUE THREAD

**Issue by gbeyer3** [conceptualspace/yet-another-speed-dial#52]
I've noticed an odd problem that the speed dials (SD) that I have saved as well as folders containing SD disappear from YASD.  I use Firefox.  When I open a new tab, I just have a blank screen.  The settings widget for YASD is there, but no dials.  If I manage bookmarks, I find the Speed Dial folder, SD's, and all sub-folders with their SD's.  It's as if YASD has lost track of where my SD's are.  Can you help?

**Comment by conceptualspace** [comment]
there is an issue where if YASD detects another speed dial folder it might be trying to use that one instead of the one you have your dials in. try opening the bookmarks manager and searching for "Speed Dial" to see if you might have any other folders with this name. If so, rename the other one and try restarting your browser.

If that doesn't work, can you see if there are any errors in the console? Go to about:debugging >  This Firefox > Yet Another Speed Dial > Inspect > Console and paste any relevant messages here

**Comment by conceptualspace** [comment]
closing pending further info
