### ISSUE TITLE
Chrome's "default bookmark folder" getting changed after adding site to speed dial tab.

### ISSUE THREAD

**Issue by CortexReaver** [conceptualspace/yet-another-speed-dial#55]
Cool plugin, but I didn't like the fact it changes your default bookmark folder, so every time you adding a site to speed dial tab via context menu its also adding bookmark to the same folder (last used by default on Chrome). So you need to bookmark some other site (and then delete it) to reset a folder to what you using. And because you not always remember if you "speed dial" a certain site you might end up with a lot of trash in your default tab, which needs to be cleaned afterwards.
Is there maybe a way to hide "Speed Dial" folder from the bookmark manager and chrome itself? Or either just not to touch the "default bookmark folder" variable? In current state it needs another plugin (for managing bookmarks) on top of this one to make it comfortable to use.

**Comment by CortexReaver** [comment]
> Chrome will remember the most recent folder you've bookmarked a site to, and YASD does not control this setting.
It in fact controls it. I can record a video to show you
![Example1](https://user-images.githubusercontent.com/34350690/154768278-12a87f9e-e378-4ca6-a438-6629c58b10d2.gif)
.

**Comment by conceptualspace** [comment]
Yes, but all the "Add to Speed Dial" menu item does is bookmark the site. It's just a shortcut to add the bookmark directly to the Speed Dial folder (the same thing as if you had clicked the star instead).

So just like when you click the star and choose some other folder, that other folder is remembered by Chrome too. You could raise the same issue anytime you use a folder with regular bookmarks -- you might forget what folder new bookmarks are going into.

Speed dials are bookmarks by design, so this is working as expected, but I will think on a way to make this more clear for users
