### ISSUE TITLE
no starting with "yasd"

### ISSUE THREAD

**Issue by klausph** [conceptualspace/yet-another-speed-dial#6]
hi
if I use keyboard with CTRL+t
I get: 

moz-extension://cc55cf6b-9eca-4499-9878-dfea210b545e/index.html
in German: Zugriff auf die Datei wurde verweigert
Die Datei auf moz-extension://cc55cf6b-9eca-4499-9878-dfea210b545e/index.html ist nicht lesbar.
Sie wurde möglicherweise entfernt, verschoben, oder Dateiberechtigungen könnten den Zugriff verhindern.

its noit possible to use yet-another-speed-dial
what have I to do?

Thanks a lot
Yours Klaus Lehmann

**Comment by conceptualspace** [comment]
It sounds like you could have another addon overriding the speed dial, or you are browsing in private mode and need to enable it.

Instructions for how to allow the addon in private browsing are here:

https://support.mozilla.org/en-US/kb/extensions-private-browsing

Alternatively, removing and re-installing Yet Another Speed Dial may also resolve the issue.

Hope that helps, and thanks for trying the addon!

Best,
Tyler

--
This email may contain confidential information and is for the sole use of the intended recipient(s). Any review or distribution by others is strictly prohibited. The information expressed or contained in this email is not given or endorsed by the sender unless otherwise affirmed independently by the sender.

From: Klaus Lehmann
Sent: August 9, 2019 8:09 AM
To: conceptualspace/yet-another-speed-dial
Cc: Subscribed
Subject: [conceptualspace/yet-another-speed-dial] no starting with "yasd" (#6)

hi
if I use keyboard with CTRL+t
I get:
moz-extension://cc55cf6b-9eca-4499-9878-dfea210b545e/index.html
in German: Zugriff auf die Datei wurde verweigert
Die Datei auf moz-extension://cc55cf6b-9eca-4499-9878-dfea210b545e/index.html ist nicht lesbar.
Sie wurde möglicherweise entfernt, verschoben, oder Dateiberechtigungen könnten den Zugriff verhindern.
its noit possible to use yet-another-speed-dial
what have I to do?
Thanks a lot
Yours Klaus Lehmann

**Comment by conceptualspace** [comment]
Oh sorry I see now, I just translated your message from the German and see it was an error message.

Do other extensions work?

Some users report this error could be related to storing your user profile on a remove drive or using firefox in an enterprise environment. Do you know if that applies to your situation? Can you confirm what version of Firefox you are running?

Thanks

**Comment by klausph** [comment]
a. its allowed to browse in privat modus.

b. deinstall. firefox off, and firefox and "yet-another-speed-dial" installed. same story: 
Zugriff auf die Datei wurde verweigert
Die Datei auf moz-extension://5ddc8304-125c-4d9e-ac32-faf9ace2f4c3/index.html ist nicht lesbar.
Sie wurde möglicherweise entfernt, verschoben, oder Dateiberechtigungen könnten den Zugriff verhindern.
info: I'm working since many years with firefox-nightly! every day a new version.
thanks. Klaus

**Comment by conceptualspace** [comment]
I'm inclined to think a bug/misconfiguration exists somewhere in FF that is preventing it from accessing the extensions directory. Since FF itself creates the appropriate directories for extensions rather than the addon there isn't anything I can do from the application side.

You could manually check the file permissions of the extension file and make sure your user has access:

`C:\Users\<USERNAME>\AppData\Roaming\Mozilla\Firefox\Profiles\<ID>.default\extensions`

Another thing you could try is creating a new firefox user profile. You will want to backup your existing profile first. Then see if the addon works with the new profile:

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

Good luck!
