### ISSUE TITLE
YASD and Vivaldi bug

### ISSUE THREAD

**Issue by HyperionEx** [conceptualspace/yet-another-speed-dial#62]
I'm using Vivaldi browser and YASD. I prefer using YASD instead of vivaldi integrated Speed Dial because it's a good alternative and it's cross compatible between Chromium browsers (i'm using chrome on other computer/systems). I just found a bug with the start page redirection of YASD? and vivaldi (i think), when trying to go to vivaldi history stats (vivaldi://history/) it doesn't display the page when YASD is enabled (i must disable YASD to make it work again). If you could try to fix this issue on the next YASD version it would be very nice. Thanks !

**Comment by conceptualspace** [comment]
what exactly happens when you go to vivaldi://history and it doesnt work? is there an error message? (going to dev console and pasting any error messages would be helpful too). i have no idea why YASD would cause that to happen, my guess is there's a bug on the vivaldi side dealing with extensions that replace the new tab page

**Comment by conceptualspace** [comment]
i'm going to close this but if you have more info that suggests its something in YASD i could fix, please feel free to reopen
