### ISSUE TITLE
Option for Chrome?

### ISSUE THREAD

**Issue by elmonster213** [conceptualspace/yet-another-speed-dial#7]
You mention it's for FF and Chrome. I can't find the extension anywhere for Chrome.

**Comment by conceptualspace** [comment]
it is still pending review by the chrome store (takes weeks). when it is published i'll add a link to the README

if you want to try it in the meantime, you can do the following:

1. Download the extension manually and extract it somewhere on your computer:
https://conceptualspace.net/yet_another_speed_dial-1.3.17.zip
2. Go to chrome://extensions
3. Click 'Developer Mode' at the top right
4. Click on the 'Load unpacked' button at the top left and browse for the folder you extracted in the first step

That should do the trick. I would suggest checking back later to see if it has been published in the store and if so use that instead so that you can continue to get regular updates.

Cheers

**Comment by elmonster213** [comment]
Working good so far in Brave browser. Ridiculous how other speed dials track. Thank you.

**Comment by conceptualspace** [comment]
FYI:

https://chrome.google.com/webstore/detail/yet-another-speed-dial/imohnlganmafcmidafklgkgfgaagiohn
