### ISSUE TITLE
Thumbnails not showing on speed dial

### ISSUE THREAD

**Issue by heywolf15** [conceptualspace/yet-another-speed-dial#9]
I do Refresh Firefox that reset add-ons and settings. I've been sync all before that and let the sync put it back, but all the thumbnail not showing. Is it possible to refresh the thumbnail?

**Comment by conceptualspace** [comment]
one workaround you can try is this:

open the firefox bookmarks manager and drag all the bookmarks out of the speed dial folder into some temporary folder. then drag them all back. the speed dial will then treat them like new speed dials and go and fetch images

what happens to cause the problem is the bookmark urls are synced by firefox, but not the extension's image urls. future versions could at least try to refresh these automatically on reset. thanks for the report

**Comment by xan2622** [comment]
Hi. 

I have also noticed that when you try to add a new thumbnail (pasting the URL of the website), the add-on opens a new tab (to take a screenshot of the website, for the thumbnail), but it doesn't refresh the **new tab** where thumbnails are displayed. 

It might be convenient to have, in the addon right click menu (over a thumbnail), an entry to **Refresh Thumbnail Image".

**Comment by conceptualspace** [comment]
added in v1.8
